# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='source_reference_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
