# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_money', '0002_auto_20170704_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionremitter',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TransactionRemitter',
        ),
    ]
